# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Pre-merge workflow

on:
  pull_request:
    branches:
      - master
      - '[0-9]+.[0-9]+.z'
      - '[0-9]+.[0-9]+.0'

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

        # Setting up JDK 11 could be time-consuming for self-hosted runner
        # depending on the internet speed of the machine
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build and run battery, unit, and functional tests
        run: |
          cd D:\synopsys-detect\
          ./gradlew clean build -Ptags="battery,unit,functional" -Pversion="${{github.event.number}}-SNAPSHOT"
